server:
  port: 8091

spring:
  application:
    name: msvc-cart
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
  config:
    import: "optional:configserver:"

eureka:
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreakers, circuitbreakerevents
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      product:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5  # Asegura que evalúe después de 5 llamadas
        failureRateThreshold: 50 # 50% de fallos activa el CB
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      product:
        maxAttempts: 3
        waitDuration: 500
        retryExceptions[0]: feign.FeignException$InternalServerError

