server:
  port: 8090

spring:
  application:
    name: msvc-product
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
  config:
    import: "optional:configserver:"

eureka:
  client:
    service-url:
      defaultZone: http://msvc-eureka-container:8761/eureka/